### ISSUE TITLE
Debug Error! abort() has been called

### ISSUE THREAD

**Issue by GraphicsEnthusiast** [man-in-black382/PathFinder#2]
Hello, I encountered a problem while running your program. Could you help me solve the problem? thank you!
![a](https://user-images.githubusercontent.com/75780167/171800676-a99ab9ca-ffb8-4955-9464-a1f273ac1c51.png)
![b](https://user-images.githubusercontent.com/75780167/171800762-633b00f1-1fcd-4eed-96b8-e0f6756cd927.png)

**Comment by qaz123w** [comment]
![c](https://user-images.githubusercontent.com/75780167/171805594-e37ca856-46b4-4c76-a0f0-125aa07eabf7.png)

**Comment by GraphicsEnthusiast** [comment]
I find the problem, I am sorry to bother you.  My device does not support D3D_FEATURE_LEVEL_12_2.
